version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://api.command-center.web.id/api/counter
      - JWT_SECRET=158243e2-ccc0-4798-a944-2a5b0d1c90f3
      - NODE_ENV=production
      - PORT=3005

    restart: always

    volumes:
      - ./uploads:/usr/src/app/uploads
